config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView, ListView
from costura.products.views import ProductListView

urlpatterns = [
    path(
        "",
        ProductListView.as_view(),
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("costura.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path('address/',    include('costura.addresses.urls', namespace='addresses')),
    path('products/',   include('costura.products.urls',  namespace='products')),
    path('checkout/',   include('costura.checkout.urls',  namespace='checkout')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

costura/checkout/urls.py
from django.urls import path
from . import views

app_name="checkout"

urlpatterns=[
    path(route='',                  view=views.checkout,                name='checkout'),
    path(route='complete',          view=views.complete_view,           name='complete'),
    path(route='userless',          view=views.userless_checkout,       name='userless'),
    path(route='userlesscomplete',  view=views.userless_complete_view,  name='userlesscomplete'),
    path(route='userorders',        view=views.orders_by_user,          name='ordersbyuser'),
    #path(route='complete', view=views.complete,   name='complete'),
]

costura/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path(route='',                              view=views.product_list,        name='list'),
    path(route='categories/',                   view=views.category_list,       name='category_list'),
    path(route='categories/add/',               view=views.category_add,        name='category_add'),
    path(route='categories/update/<slug:slug>/',view=views.category_update,     name='category_update'),
    path(route='categories/<slug:slug>/',       view=views.product_category,    name='product_by_category'),
    path(route='add/',                          view=views.product_add,         name='add'),
    path(route='search/',                       view=views.product_search,      name='search_results'),
    path(route='<slug:slug>/',                  view=views.product_detail,      name='detail'),
    path(route='<slug:slug>/delete/',           view=views.product_delete,      name='delete'),
    path(route='<slug:slug>/update/',           view=views.product_update,      name='update'),
    path(route='<slug:slug>/deactivate/',       view=views.product_deactivate,  name='deactivate'),
]

costura/users/urls.py
from django.urls import path
from . import views
from costura.users.views import (
    admin_create_view,
    staff_create_view,
    staff_list_view,
    customer_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
    password_change_view,
)

app_name = "users"
urlpatterns = [
    path("adminsignup/",     view=admin_create_view,      name="adminsignup"),
    path("redirect/",        view=user_redirect_view,     name="redirect"),
    path("staff/",           view=staff_list_view,        name="stafflist"),
    path("staffsignup/",     view=staff_create_view,      name="staffsignup"),
    path("customers/",       view=customer_list_view,     name="customerlist"),
    path("~update/",         view=user_update_view,       name="update"),
    path('~changepass/',     view=password_change_view,   name="change_password"),
    path("<str:username>/",  view=user_detail_view,       name="detail"),
]

itelie/users/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from itelie.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/",      view=user_redirect_view,name="redirect"),
    path("~update/",        view=user_update_view,  name="update"),
    path("<str:username>/", view=user_detail_view,  name="detail"),
]

costura/addresses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.urls import reverse_lazy
from .models import Address

address_fields = [
        "receiver_name",
        "receiver_phone",
        "nickname",
        "address_type",
        "state",
        "city",
        "neighborhood",
        "street",
        "number",
        "extra_data",
    ]


class LimitAccessMixin:     #Created in order to return only adresses from the logged user
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(owned_by=self.request.user)

class AddressDetailView(LimitAccessMixin, DetailView):
    model = Address

class AddressCreateView(LoginRequiredMixin, CreateView):
    model  = Address
    fields = address_fields
    success_url = reverse_lazy('addresses:list')
    action = "Adicionar"

    def form_valid(self, form):
        form.instance.creator = self.request.user
        form.instance.owned_by = self.request.user
        return super(AddressCreateView, self).form_valid(form)

class AddressListView(LimitAccessMixin, LoginRequiredMixin, ListView):
    model = Address

class AddressUpdateView(LoginRequiredMixin, UpdateView):
    model  = Address
    fields = address_fields
    success_url = reverse_lazy('addresses:list')
    action = "Atualizar"

    def form_valid(self, form):
        form.instance.creator = self.request.user
        form.instance.owned_by = self.request.user
        return super(AddressUpdateView, self).form_valid(form)
    
    

costura/checkout/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import modelformset_factory
from django.http import request
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, TemplateView, ListView

from costura.products.models import Product

from .models import Order, UserlessOrder

class CheckoutView(LoginRequiredMixin, TemplateView):
    template_name = 'checkout/checkout.html'
    def post(self,request, *args, **kwargs):
        items   = request.POST.get('items','')
        address = request.POST.get('address',"")
        total   = request.POST.get('total',"")
        obs     = request.POST.get('obs',"")
        order = Order.objects.create_order(items=items, user=request.user, address=address,total=total,obs=obs)
        order.save()
        response = super(CheckoutView, self).get(request, *args, **kwargs)
        response.context_data['order'] = order
        return response

complete_view = CheckoutView.as_view()


class UserlessCheckoutView(TemplateView):
    template_name = 'checkout/checkout.html'
    def post(self,request, *args, **kwargs):
        items   = request.POST.get('items','')
        address = request.POST.get('address',"")
        total   = request.POST.get('total',"")
        final   = request.POST.get('final',"")
        ship   = request.POST.get('ship',"")
        cpf   = request.POST.get('cpf',"")
        obs     = request.POST.get('obs',"")
        phone   = request.POST.get('phone',"")
        order = UserlessOrder.objects.create_order(tems=items,address=address,total=total,final=final,ship=ship,cpf=cpf,obs=obs,phone=phone,user=None)
        order.save()
        response = super(UserlessCheckoutView, self).get(request, *args, **kwargs)
        response.context_data['order'] = order
        return response

userless_complete_view = UserlessCheckoutView.as_view()

def checkout(request):
    order = None
    if request.method == "POST":
        items   = request.POST.get('items','')
        address = request.POST.get('address',"")
        total   = request.POST.get('total',"")
        obs     = request.POST.get('obs',"")
        user    = request.user
        order   = Order(items=items,address=address,user=user,total=total,obs=obs)
        order.save()
        order   = order
        return render(request,'checkout/checkout.html',{'order':order})
    return render(request,'checkout/cart_detail.html',{'order':order})

def complete(request):
    return render(request,'checkout/checkout.html')

def userless_checkout(request):
    order = None
    if request.method == "POST":
        items   = request.POST.get('items','')
        address = request.POST.get('address',"")
        total   = request.POST.get('total',"")
        final   = request.POST.get('final',"")
        ship    = request.POST.get('ship',"")
        obs     = request.POST.get('obs',"")
        cpf     = request.POST.get('cpf',"")
        phone   = request.POST.get('phone',"")
        order   = UserlessOrder(items=items,address=address,total=total,final=final,ship=ship,cpf=cpf,obs=obs,phone=phone,user=None)
        order.save()
        order   = order
        return render(request,'checkout/userless_checkout.html',{'order':order})
    return render(request,'checkout/cart_detail.html',{'order':order})


class UserlessView(TemplateView):
    template_name = 'checkout/userless_checkout.html'
    def post(self,request, *args, **kwargs):
        items   = request.POST.get('items','')
        address = request.POST.get('address',"")
        total   = request.POST.get('total',"")
        obs     = request.POST.get('obs',"")
        order = Order.objects.create_order(items=items, user='None', address=address,total=total,obs=obs)
        order.save()
        response = super(UserlessView, self).get(request, *args, **kwargs)
        response.context_data['order'] = order
        return response
               
#userless = UserlessView.as_view()

class OrdersByUserView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'checkout/orders.html'
    def get_queryset(self):
        order_list = Order.objects.filter(user=self.request.user)
        return order_list
    
orders_by_user = OrdersByUserView.as_view()

"""
class CheckoutView(LoginRequiredMixin, TemplateView):
    template_name = 'checkout/checkout.html'

    def get(self, request, *args, **kwargs):
        session_key = request.session.session_key
        if session_key and CartItem.objects.filter(cart_key=session_key).exists():
            cart_items = CartItem.objects.filter(cart_key=session_key)
            order = Order.objects.create_order(
                user=request.user, cart_items=cart_items
            )
        else:
            messages.info(request, 'Não há itens no carrinho de compras')
            return redirect('checkout:cart_item')
        response = super(CheckoutView, self).get(request, *args, **kwargs)
        response.context_data['order'] = order
        return response

checkout        = CheckoutView.as_view()

class OrdersByUserView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'checkout/orders.html'
    
    def get_queryset(self):
        user_name = self.request.user.username
        order_list = Order.objects.filter(username=user_name)
        return order_list
    
orders_by_user = OrdersByUserView.as_view()
"""

costura/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

costura/users/views.py
from allauth.account.views import PasswordChangeView as allauth_PasswordChangeView
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DetailView, RedirectView, TemplateView, UpdateView, ListView
from .models import Customer, Staff
from .forms import AdminCreationForm, StaffCreationForm, UserChangeForm

User = get_user_model()

class SuperUserRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser
    
class AdminRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_admin

class UserListView(ListView):
    model = User
    
class CustomerListView(AdminRequiredMixin, ListView):
    model = User
    template_name = 'users/user_list.html'
    def get_queryset(self):
        return User.objects.filter(is_customer=True)
    
customer_list_view = CustomerListView.as_view()

class StaffListView(AdminRequiredMixin, ListView):
    model = User
    template_name = 'users/user_list.html'
    def get_queryset(self):
        return User.objects.filter(is_staff=True)

staff_list_view = StaffListView.as_view()

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

class PasswordChangeView(LoginRequiredMixin, allauth_PasswordChangeView):
    
    def get_success_url(self):
        return reverse(
            "users:detail",
            kwargs={'username': self.request.user.username},
        )

password_change_view = PasswordChangeView.as_view()

class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserChangeForm

    def get_success_url(self):
        return reverse(
            "users:detail",
            kwargs={'username': self.request.user.username},
        )

    def get_object(self):
        # Only Get the User Record for the
        #   User Making the Request
        return User.objects.get(
            username=self.request.user.username
        )

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Credenciais Aualizadas com sucesso")
        )
        return super().form_valid(form)

class UserRedirectViews(RedirectView):
    permanent = False
    def get_redirect_url(self):
        return reverse(
            "users:detail",
            kwargs={"username": self.request.user.username},
        )
        
class UserRedirectView(RedirectView):
    permanent = False
    def get_redirect_url(self):
        return reverse(
            "products:list",
        )

user_detail_view   = UserDetailView.as_view()
user_update_view   = UserUpdateView.as_view()
user_redirect_view = UserRedirectView.as_view()


    
class AdminCreateView(SuperUserRequiredMixin, CreateView):
    model = User
    form_class = AdminCreationForm
    template_name = 'account/signup_admin.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'admin'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        return redirect('users:redirect')
    
admin_create_view = AdminCreateView.as_view()


class StaffCreateView(AdminRequiredMixin, CreateView):
    model = User
    form_class = StaffCreationForm
    template_name = 'account/signup_staff.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'staff'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        return redirect('users:redirect')

staff_create_view = StaffCreateView.as_view()

costura/templates/users/staff_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Adicionar Funcionario | {{ block.super }}{% endblock %}

{% block content %}
  <h1>{{ user.name }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:staffsignup' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Adicionar Funcionário</button>
      </div>
    </div>
  </form>
{% endblock %}

costura/templates/users/user_detail.html
{% extends "base.html" %} 
{% load static %} 
{% block title %}
{{ object.username}} | {{ block.super }}
{% endblock %} 

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h2>
        Olá,
        {% if object.first_name %}
          {% if object.prefix %}  
            {{object.prefix}}  {{object.get_fullname}} 
          {% else %} 
            {{object.get_fullname}}
          {% endif %} 
        {% endif %}
      </h2>
      <div class="table-responsive">
        <table class="table">
          <tbody>
            <tr>
              <th scope="row">Prefixo:</th>
              <td>
                {% if object.prefix %} {{ object.prefix }} {% endif %}
              </td>
            </tr>
            <tr>
              <th scope="row">Nome:</th>
              <td>
                {% if object.first_name %} {{ object.first_name }} {% endif %}
              </td>
            </tr>
            <tr>
              <th scope="row">Sobrenome:</th>
              <td>
                {% if object.last_name %} {{ object.last_name }} {% endif %}
              </td>
            </tr>
            <tr>
              <th scope="row">CPF:</th>
              <td>{% if object.cpf %} {{ object.cpf }} {% endif %}</td>
            </tr>
            <tr>
              <th scope="row">E-Mail Primário:</th>
              <td>
                {{ object.email }}
              </td>
            </tr>
            <tr>
              <th scope="row">Data de Nascimento:</th>
              <td>{% if object.dob %} {{ object.dob }} {% endif %}</td>
            </tr>
            <tr>
              <th scope="row">Data de Cadastro:</th>
              <td>{{ object.join_date }}</td>
            </tr>
            {% if object.phone %}
            <tr>
              <th scope="row">Telefone para contato:</th>
              <td> {{ object.phone }} </td>
            </tr>
            {% endif %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

  {% if object == request.user %}
  <!-- Action buttons -->
  <div class="row">
    <div class="col-sm-12">
      <a
        class="btn btn-outline-primary"
        href="{% url 'users:update' %}"
        role="button"
        >Atualizar Perfil</a
      >
      <a
        class="btn btn-outline-info"
        href="{% url 'account_email' %}"
        role="button"
        >Contas de E-Mail</a
      >

      <a
        class="btn btn-outline-secondary"
        href="{% url 'addresses:list' %}"
        role="button"
        >Endereços</a
      >
      <a class="btn btn-outline-success" href="{% url 'checkout:ordersbyuser' %}" role="button"
        >Meus Pedidos</a
      >
    </div>
  </div>
  <!-- End Action buttons -->
  {% endif %}
</div>
{% endblock content %}

costura/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }} | {{ block.super }}{% endblock %}

{% block content %}
  <h1>Perfil de <em>{{ user.get_fullname }}</em></h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Atualizar Info</button>
      </div>
    </div>
  </form>
  <br>
  <a
  class="btn btn-outline-info"
  href="{% url 'account_change_password' %}"
  role="button"
  >Mudar Senha</a
  >
  <h2>
    Deseja modificar as informações desabilitadas?
  </h2>
  <a href="#TODO-CONTACTSUPPORT"><button type="submit" class="btn btn-secondary">Contactar Suporte Técnico</button></a>
{% endblock %}

costura/templates/users/user_list.html
{% extends "base.html" %} 
{% block title %} Gerenciar | {{block.super }}
{% endblock title %} 
{% block pageheader %}
<div class="page-header text-center mb-4">
  <h1>Listar Usuários</h1>
</div>
{% endblock pageheader %} 

{% block content %}
<div class="table-responsive">
  <table class="table">
      <tbody style="text-align: center;">
          <tr>
            <th> Username </th>
            <th> Nome </th>
            <th> E-Mail </th>
            <th> Membro Desde </th>
            <th> Pedidos </th>
        </tr>
        {% for user in user_list %}
        <tr>
            <td>{{user.username}}</td>
            <td>{{user.first_name}} {{user.last_name}}</td>
            <td>{{user.email}}</td>
            <td>{{user.join_date}}</td>
            <td><a href="#TODO"><span class="jam jam-document"></span></a></td>
        </tr>
        {% endfor %}
      </tbody>
  </table>
</div>
{% endblock content %}