config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView, ListView
from costura.products.views import ProductListView

urlpatterns = [
    path(
        "",
        ProductListView.as_view(),
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("costura.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path('address/',    include('costura.addresses.urls', namespace='addresses')),
    path('products/',   include('costura.products.urls',  namespace='products')),
    path('checkout/',   include('costura.checkout.urls',  namespace='checkout')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

costura/checkout/urls.py
from django.urls import path
from . import views

app_name="checkout"

urlpatterns=[
    path(route='',                  view=views.checkout,                name='checkout'),
    path(route='complete',          view=views.complete_view,           name='complete'),
    path(route='userless',          view=views.userless_checkout,       name='userless'),
    path(route='userlesscomplete',  view=views.userless_complete_view,  name='userlesscomplete'),
    path(route='userorders',        view=views.orders_by_user,          name='ordersbyuser'),
    #path(route='complete', view=views.complete,   name='complete'),
]

costura/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path(route='',                              view=views.product_list,        name='list'),
    path(route='categories/',                   view=views.category_list,       name='category_list'),
    path(route='categories/add/',               view=views.category_add,        name='category_add'),
    path(route='categories/update/<slug:slug>/',view=views.category_update,     name='category_update'),
    path(route='categories/<slug:slug>/',       view=views.product_category,    name='product_by_category'),
    path(route='add/',                          view=views.product_add,         name='add'),
    path(route='search/',                       view=views.product_search,      name='search_results'),
    path(route='<slug:slug>/',                  view=views.product_detail,      name='detail'),
    path(route='<slug:slug>/delete/',           view=views.product_delete,      name='delete'),
    path(route='<slug:slug>/update/',           view=views.product_update,      name='update'),
    path(route='<slug:slug>/deactivate/',       view=views.product_deactivate,  name='deactivate'),
]

costura/users/urls.py
from django.urls import path
from . import views
from costura.users.views import (
    admin_create_view,
    staff_create_view,
    staff_list_view,
    customer_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
    password_change_view,
)

app_name = "users"
urlpatterns = [
    path("adminsignup/",     view=admin_create_view,      name="adminsignup"),
    path("redirect/",        view=user_redirect_view,     name="redirect"),
    path("staff/",           view=staff_list_view,        name="stafflist"),
    path("staffsignup/",     view=staff_create_view,      name="staffsignup"),
    path("customers/",       view=customer_list_view,     name="customerlist"),
    path("~update/",         view=user_update_view,       name="update"),
    path('~changepass/',     view=password_change_view,   name="change_password"),
    path("<str:username>/",  view=user_detail_view,       name="detail"),
]

costura/checkout/models.py
from django.db import models
#from costura.products.models import Product
from django.conf import settings
from model_utils.models import TimeStampedModel
from django_extensions.db.fields import AutoSlugField
from django.urls import reverse
from ..users.validators import validate_cpf

class Order(TimeStampedModel):
    STATUS_CHOICES = (
        (0, "Aguardando Pagamento"),
        (1, "Compra Concluída"),
        (2, "Compra CANCELADA"),
    )
    slug    = AutoSlugField("Registro digital", unique=True, populate_from="pk")
    user    = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name="Usuário", on_delete=models.CASCADE)
    status  = models.IntegerField("Situação", choices=STATUS_CHOICES,default=0, blank=True)
    items   = models.CharField(max_length=1000)
    payment_option   = models.CharField(max_length=1000, default='Deposito')
    address = models.CharField(max_length=1000)
    total   = models.CharField(max_length=200)
    obs     = models.CharField(max_length=200, default='')

    class Meta:
        verbose_name = "Pedido"
        verbose_name_plural = "Pedidos"

    def __str__(self):
        return f"Pedido # {self.pk}"
    
    def get_absolute_url(self):
        return reverse('checkout:complete',kwargs={'slug':self.slug})
    
class UserlessOrder(TimeStampedModel):
    STATUS_CHOICES = (
        (0, "Aguardando Pagamento"),
        (1, "Compra Concluída"),
        (2, "Compra CANCELADA"),
    )
    slug    = AutoSlugField("Registro digital", unique=True, populate_from="pk")
    user    = None
    status  = models.IntegerField("Situação", choices=STATUS_CHOICES,default=0, blank=True)
    items   = models.CharField(max_length=1000)
    payment_option   = models.CharField(max_length=1000, default='Deposito')
    address = models.CharField(max_length=1000)
    total   = models.CharField(max_length=200)
    ship    = models.CharField(max_length=200)
    final   = models.CharField(max_length=200)
    obs     = models.CharField(max_length=200, default='')
    cpf     = models.CharField(("CPF"), max_length=14, validators=[validate_cpf])#,unique=True)
    phone   = models.CharField(("Telefone"), max_length=13, null=True)#,unique=True)
    
    class Meta:
        verbose_name = "Pedido sem Usuário"
        verbose_name_plural = "Pedidos sem Usuário"

    def __str__(self):
        return f"Pedido (S.U) # {self.pk}"

    def get_absolute_url(self):
        return reverse('checkout:userlesscomplete',kwargs={'slug':self.slug})

costura/users/models.py
import re

from django.contrib.auth.models import AbstractBaseUser, AbstractUser, PermissionsMixin, UserManager
from django.db import models
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .validators import username_validator, validate_cpf

class User(AbstractUser,PermissionsMixin):
    is_superuser = models.BooleanField(default=False)
    is_admin     = models.BooleanField(default=False)
    is_staff     = models.BooleanField(default=False)
    is_customer  = models.BooleanField(default=False)
    is_active    = models.BooleanField(default=True)
    join_date    = models.DateField(auto_now_add=True)
    prefix       = models.CharField(_("Prefixo / Apelido"), max_length=8, blank=True)
    cpf          = models.CharField(_("CPF"), max_length=14, validators=[validate_cpf])#,unique=True)
    dob          = models.DateField("Data de Nascimento", null=True)
    phone        = models.CharField(_("Telefone"), max_length=13, null=True)#,unique=True)

    def get_absolute_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.first_name}
        )

    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Usuários"

    def __str__(self):
        return self.first_name 

    def get_fullname(self):
        return self.first_name + ' ' + self.last_name
    
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email','first_name','last_name','cpf','dob','phone']

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    
    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        
    def __str__(self):
        return self.user.username

class Staff(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    
    class Meta:
        verbose_name = "Colaborador"
        verbose_name_plural = "Colaboradores"
        
    def __str__(self):
        return self.user.username

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    class Meta:
        verbose_name = "Administrador"
        verbose_name_plural = "Administradores"
        
    def __str__(self):
        return self.user.username

costura/addresses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.urls import reverse_lazy
from .models import Address

address_fields = [
        "receiver_name",
        "receiver_phone",
        "nickname",
        "address_type",
        "state",
        "city",
        "neighborhood",
        "street",
        "number",
        "extra_data",
    ]


class LimitAccessMixin:     #Created in order to return only adresses from the logged user
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(owned_by=self.request.user)

class AddressDetailView(LimitAccessMixin, DetailView):
    model = Address

class AddressCreateView(LoginRequiredMixin, CreateView):
    model  = Address
    fields = address_fields
    success_url = reverse_lazy('addresses:list')
    action = "Adicionar"

    def form_valid(self, form):
        form.instance.creator = self.request.user
        form.instance.owned_by = self.request.user
        return super(AddressCreateView, self).form_valid(form)

class AddressListView(LimitAccessMixin, LoginRequiredMixin, ListView):
    model = Address

class AddressUpdateView(LoginRequiredMixin, UpdateView):
    model  = Address
    fields = address_fields
    success_url = reverse_lazy('addresses:list')
    action = "Atualizar"

    def form_valid(self, form):
        form.instance.creator = self.request.user
        form.instance.owned_by = self.request.user
        return super(AddressUpdateView, self).form_valid(form)
    
    

costura/checkout/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import modelformset_factory
from django.http import request
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, TemplateView, ListView

from costura.products.models import Product

from .models import Order, UserlessOrder

class CheckoutView(LoginRequiredMixin, TemplateView):
    template_name = 'checkout/checkout.html'
    def post(self,request, *args, **kwargs):
        items   = request.POST.get('items','')
        address = request.POST.get('address',"")
        total   = request.POST.get('total',"")
        obs     = request.POST.get('obs',"")
        order = Order.objects.create_order(items=items, user=request.user, address=address,total=total,obs=obs)
        order.save()
        response = super(CheckoutView, self).get(request, *args, **kwargs)
        response.context_data['order'] = order
        return response

complete_view = CheckoutView.as_view()


class UserlessCheckoutView(TemplateView):
    template_name = 'checkout/checkout.html'
    def post(self,request, *args, **kwargs):
        items   = request.POST.get('items','')
        address = request.POST.get('address',"")
        total   = request.POST.get('total',"")
        final   = request.POST.get('final',"")
        ship   = request.POST.get('ship',"")
        cpf   = request.POST.get('cpf',"")
        obs     = request.POST.get('obs',"")
        phone   = request.POST.get('phone',"")
        order = UserlessOrder.objects.create_order(tems=items,address=address,total=total,final=final,ship=ship,cpf=cpf,obs=obs,phone=phone,user=None)
        order.save()
        response = super(UserlessCheckoutView, self).get(request, *args, **kwargs)
        response.context_data['order'] = order
        return response

userless_complete_view = UserlessCheckoutView.as_view()

def checkout(request):
    order = None
    if request.method == "POST":
        items   = request.POST.get('items','')
        address = request.POST.get('address',"")
        total   = request.POST.get('total',"")
        obs     = request.POST.get('obs',"")
        user    = request.user
        order   = Order(items=items,address=address,user=user,total=total,obs=obs)
        order.save()
        order   = order
        return render(request,'checkout/checkout.html',{'order':order})
    return render(request,'checkout/cart_detail.html',{'order':order})

def complete(request):
    return render(request,'checkout/checkout.html')

def userless_checkout(request):
    order = None
    if request.method == "POST":
        items   = request.POST.get('items','')
        address = request.POST.get('address',"")
        total   = request.POST.get('total',"")
        final   = request.POST.get('final',"")
        ship    = request.POST.get('ship',"")
        obs     = request.POST.get('obs',"")
        cpf     = request.POST.get('cpf',"")
        phone   = request.POST.get('phone',"")
        order   = UserlessOrder(items=items,address=address,total=total,final=final,ship=ship,cpf=cpf,obs=obs,phone=phone,user=None)
        order.save()
        order   = order
        return render(request,'checkout/userless_checkout.html',{'order':order})
    return render(request,'checkout/cart_detail.html',{'order':order})


class UserlessView(TemplateView):
    template_name = 'checkout/userless_checkout.html'
    def post(self,request, *args, **kwargs):
        items   = request.POST.get('items','')
        address = request.POST.get('address',"")
        total   = request.POST.get('total',"")
        obs     = request.POST.get('obs',"")
        order = Order.objects.create_order(items=items, user='None', address=address,total=total,obs=obs)
        order.save()
        response = super(UserlessView, self).get(request, *args, **kwargs)
        response.context_data['order'] = order
        return response
               
#userless = UserlessView.as_view()

class OrdersByUserView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'checkout/orders.html'
    def get_queryset(self):
        order_list = Order.objects.filter(user=self.request.user)
        return order_list
    
orders_by_user = OrdersByUserView.as_view()

"""
class CheckoutView(LoginRequiredMixin, TemplateView):
    template_name = 'checkout/checkout.html'

    def get(self, request, *args, **kwargs):
        session_key = request.session.session_key
        if session_key and CartItem.objects.filter(cart_key=session_key).exists():
            cart_items = CartItem.objects.filter(cart_key=session_key)
            order = Order.objects.create_order(
                user=request.user, cart_items=cart_items
            )
        else:
            messages.info(request, 'Não há itens no carrinho de compras')
            return redirect('checkout:cart_item')
        response = super(CheckoutView, self).get(request, *args, **kwargs)
        response.context_data['order'] = order
        return response

checkout        = CheckoutView.as_view()

class OrdersByUserView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'checkout/orders.html'
    
    def get_queryset(self):
        user_name = self.request.user.username
        order_list = Order.objects.filter(username=user_name)
        return order_list
    
orders_by_user = OrdersByUserView.as_view()
"""

costura/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

costura/templates/checkout/_cart.html
{% load widget_tweaks %}
<div class="row">
    <div class="col-md-12 col-md-offset-2">
        <form class="" action="" method="post">
            {{ formset.management_form }}
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead class="text-center">
                        <th>
                            ID
                        </th>
                        <th>
                            Nome
                        </th>
                        <th>
                            Preço
                        </th>
                        <th>
                            Preço Promocional
                        </th>
                        <th style="width: 10%;">
                            Quantidade
                        </th>
                        <th style="width: 10%;" >
                            Remover
                        </th>
                    </thead>
                    <tbody>
                        {% for form in formset %}
                        <tr>
                            <td>
                                {{ form.instance.product.pk }}
                            </td>
                            <td>
                                <a href="{% url 'products:detail' form.instance.product.slug %}">{{ form.instance.product }}</a>
                            </td>
                            <td>
                                {% if form.instance.discount_price %}
                                    R$ {{ form.instance.discount_price }}
                                {% else %}
                                    R$ {{ form.instance.price }}
                                    {% endif %}
                            </td>
                            <td>
                                {% render_field form.quantity class='form-control' %}
                            </td>
                            <td class="text-center">
                                <button value="on" type="submit" name="{{ form.DELETE.html_name }}" class="btn btn-danger btn-sm"><span class="jam jam-trash"></span></button>
                                {{ form.id }}
                            </td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <td colspan="5">
                                Preço Final
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <p class="text-right">
                <a href="{% url 'products:list' %}" class="pull-left btn btn-default">Continuar Compras</a>
                <button type="submit" class="btn btn-primary" name="button">Atualizar Carrinho</button></li>
                <a href="#TODOFinalizarCompra"  class="btn btn-success">Finalizar Compra</a>
            </p>
        </form>
    </div>
</div>

costura/templates/checkout/cart_detail copy.html
{% extends "base.html" %} 
{% block title %} Carrinho | {{block.super}} {% endblock title%} 
{% load static %}
{% load widget_tweaks %}

<h1>Seu carrinho:</h1>

{% block content %}
<div class="row">
    <div class="col-md-12 col-md-offset-2">
        <form class="" action="" method="post">
            {% csrf_token %}
            {{ formset.management_form }}
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead class="text-center">
                        <th>
                            ID
                        </th>
                        <th>
                            Nome
                        </th>
                        <th>
                            Preço
                        </th>
                        <th>
                            Preço Promocional
                        </th>
                        <th style="width: 10%;">
                            Quantidade
                        </th>
                        <th style="width: 10%;" >
                            Remover
                        </th>
                    </thead>
                    <tbody>
                        {% for form in formset %}
                        <tr>
                            <td>
                                {{ form.instance.product.pk }}
                            </td>
                            <td>
                                <a href="{% url 'products:detail' form.instance.product.slug %}">{{ form.instance.product }}</a>
                            </td>
                            <td>
                                {% if form.instance.discount_price %}
                                    R$ {{ form.instance.discount_price }}
                                {% else %}
                                    R$ {{ form.instance.price }}
                                    {% endif %}
                            </td>
                            <td>
                                {% render_field form.quantity class='form-control' %}
                            </td>
                            <td class="text-center">
                                <button value="on" type="submit" name="{{ form.DELETE.html_name }}" class="btn btn-danger btn-sm"><span class="jam jam-trash"></span></button>
                                {{ form.id }}
                            </td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <td colspan="5">
                                Preço Final
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <p class="text-right">
                <a href="{% url 'products:list' %}" class="pull-left btn btn-default">Continuar Compras</a>
                <button type="submit" class="btn btn-primary" name="button">Atualizar Carrinho</button></li>
                <a href="#TODOFinalizarCompra"  class="btn btn-success">Finalizar Compra</a>
            </p>
        </form>
    </div>
</div>
{% endblock content %}
{% block javascript %}
    <script type="text/javascript">
        if(localStorage.getItem('cart')==null){
            var cart ={};
        }
        else{
            cart = JSON.parse(localStorage.getItem('cart'));
        }
        let total = 0;
        for(item in cart){
          let quantity = cart[item][0];
          let name     = cart[item][1];
          let price    = cart[item][2];
          total        = total + cart[item][2];
          itemString   = `  <li class="list-group-item d-flex justify-content-between align-items-center">${quantity} of  ${name}     <span class="badge badge-warning badge-pill">${price}</span></li>`;
          $('#item_list').append(itemString);
        }
        totalPrice = ` <li class ="list-group-item d-flex justify-content-between align-items-center"><b>Your total</b>
        ${total}</li> `
        $('#total').val(total);
        $('#item_list').append(totalPrice);
        $('#items').val(JSON.stringify(cart));
    </script>
{% endblock javascript %}

costura/templates/checkout/checkout.html
{% extends "base.html" %}

{% block title %}
Finalização da Compra
{% endblock %}

{% block content %}
{% load static %}

<div class="page-header">
    <h1>Finalização da Compra</h1>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-success">
            <h3 style="text-align: center;">O Pedido # {{order.id}} foi realizado com Sucesso!</h3>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="row m-6">
          </div>
          <ul class="list-group" id="item_list"></ul>
          <ul class="list-group">
              <li>{{order}}</li>
              <li>Total R${{order.total}}</li>
              <li>Produtos {{order.items}}</li>
          </ul>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-md-12">
        <div class="jumbotron">
            <div class="container">
                <h5>Para realizar o pagamento efetue o depósito na seguinte conta:</h5>
                <ul>
                    <li>Agência: 6616</li>
                    <li>Conta : 045847-1</li>
                    <li>Conta Corrente</li>
                    <li>Proprietário: Dono Da Empresa</li>
                </ul>
                <br>
                <br>
                <br>
                    <div class="alert alert-info">
                        <h3 style="text-align: center;">Agradecemos a Confiança!</h3>
                    </div>
          </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
{{block.super}}
<script type="text/javascript">
  let mycart = localStorage.getItem('cart');
  $("#item_list").val(mycart);
  localStorage.clear();
</script>

{% endblock javascript %}

costura/templates/checkout/orders.html
{% extends "base.html" %} 
{% block title %} Pedidos | {{block.super}}{% endblock title %} 
{% block content %}
<h1 style="text-align: center;">Seus Pedidos:</h1>
{% for order in order_list %}
<div class="row">
    <div class="col">
    <div class="card">
        <h3 class="card-header text-center">{{order}}</h3>
        <p>Produtos : {{order.items}}</p>
        <p>Método de Pagamento : {{order.payment_option}}</p>
        <p><strong>Total do Pedido : R$ {{order.total}}</strong></p> 
        <p class="card-footer text-center">Data: {{order.created}}</p> 
    </div>
    </div>
</div>
{% endfor%}
{% endblock content %}